from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 600)
        self.TEXT = QtWidgets.QTextBrowser(Dialog)
        self.TEXT.setGeometry(QtCore.QRect(10, 470, 191, 111))
        self.TEXT.setObjectName("TEXT")
        self.imgLabel = QtWidgets.QLabel(Dialog)
        self.imgLabel.setGeometry(QtCore.QRect(210, 120, 571, 471))
        self.imgLabel.setAutoFillBackground(False)
        self.imgLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        self.SHOW = QtWidgets.QPushButton(Dialog)
        self.SHOW.setGeometry(QtCore.QRect(10, 140, 191, 81))
        self.SHOW.setObjectName("SHOW")
        self.CAPTURE = QtWidgets.QPushButton(Dialog)
        self.CAPTURE.setGeometry(QtCore.QRect(10, 220, 191, 81))
        self.CAPTURE.setObjectName("CAPTURE")
        self.NEXT = QtWidgets.QPushButton(Dialog)
        self.NEXT.setGeometry(QtCore.QRect(680, 32, 161, 81))
        self.NEXT.setObjectName("NEXT")
        self.imgLabel_2 = QtWidgets.QLabel(Dialog)
        self.imgLabel_2.setGeometry(QtCore.QRect(0, 0, 1922, 30))
        self.imgLabel_2.setAutoFillBackground(False)
        self.imgLabel_2.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel_2.setText("")
        self.imgLabel_2.setPixmap(QtGui.QPixmap("ngang1.png"))
        self.imgLabel_2.setObjectName("imgLabel_2")

        self.imgLabel_3 = QtWidgets.QLabel(Dialog)
        self.imgLabel_3.setGeometry(QtCore.QRect(825, 115, 180, 120))
        self.imgLabel_3.setAutoFillBackground(False)
        self.imgLabel_3.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel_3.setText("")
        self.imgLabel_3.setObjectName("imgLabel_3")

        self.imgLabel_4 = QtWidgets.QLabel(Dialog)
        self.imgLabel_4.setGeometry(QtCore.QRect(825, 235, 180, 120))
        self.imgLabel_4.setAutoFillBackground(False)
        self.imgLabel_4.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel_4.setText("")
        self.imgLabel_4.setObjectName("imgLabel_4")

        self.imgLabel_5 = QtWidgets.QLabel(Dialog)
        self.imgLabel_5.setGeometry(QtCore.QRect(825, 355,180,  120))
        self.imgLabel_5.setAutoFillBackground(False)
        self.imgLabel_5.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel_5.setText("")
        self.imgLabel_5.setObjectName("imgLabel_5")

        self.imgLabel_6 = QtWidgets.QLabel(Dialog)
        self.imgLabel_6.setGeometry(QtCore.QRect(825, 475, 180, 120))
        self.imgLabel_6.setAutoFillBackground(False)
        self.imgLabel_6.setFrameShape(QtWidgets.QFrame.Box)
        self.imgLabel_6.setText("")
        self.imgLabel_6.setObjectName("imgLabel_6")




        self.NEXT_2 = QtWidgets.QPushButton(Dialog)
        self.NEXT_2.setGeometry(QtCore.QRect(0, 32, 181, 81))
        self.NEXT_2.setObjectName("NEXT_2")
        self.NEXT_4 = QtWidgets.QPushButton(Dialog)
        self.NEXT_4.setGeometry(QtCore.QRect(180, 32, 171, 81))
        self.NEXT_4.setObjectName("NEXT_4")
        self.NEXT_5 = QtWidgets.QPushButton(Dialog)
        self.NEXT_5.setGeometry(QtCore.QRect(350, 32, 171, 81))
        self.NEXT_5.setObjectName("NEXT_5")
        self.CAPTURE_2 = QtWidgets.QPushButton(Dialog)
        self.CAPTURE_2.setGeometry(QtCore.QRect(10, 300, 191, 81))
        self.CAPTURE_2.setObjectName("CAPTURE_2")
        self.CAPTURE_3 = QtWidgets.QPushButton(Dialog)
        self.CAPTURE_3.setGeometry(QtCore.QRect(520, 32, 161, 81))
        self.CAPTURE_3.setObjectName("CAPTURE_3")
        self.NEXT_3 = QtWidgets.QPushButton(Dialog)
        self.NEXT_3.setGeometry(QtCore.QRect(10, 380, 191, 81))
        self.NEXT_3.setObjectName("NEXT_3")
        self.NEXT_7 = QtWidgets.QPushButton(Dialog)
        self.NEXT_7.setGeometry(QtCore.QRect(840, 32, 161, 81))
        self.NEXT_7.setObjectName("NEXT_7")
        self.TEXT.raise_()
        self.imgLabel.raise_()
        self.SHOW.raise_()
        self.NEXT.raise_()
        self.imgLabel_3.raise_()
        self.NEXT_2.raise_()
        self.NEXT_4.raise_()
        self.NEXT_5.raise_()
        self.imgLabel_2.raise_()
        self.CAPTURE.raise_()
        self.CAPTURE_2.raise_()
        self.CAPTURE_3.raise_()
        self.NEXT_3.raise_()
        self.NEXT_7.raise_()
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.SHOW.setText(_translate("Dialog", "Show"))
        self.CAPTURE.setText(_translate("Dialog", "Capture"))
        self.NEXT.setText(_translate("Dialog", "Zomm-"))
        self.NEXT_2.setText(_translate("Dialog", "Chọn thiết bị"))
        self.NEXT_4.setText(_translate("Dialog", "Tùy chọn"))
        self.NEXT_5.setText(_translate("Dialog", "Thêm mới"))
        self.CAPTURE_2.setText(_translate("Dialog", "VideoRecoder"))
        self.CAPTURE_3.setText(_translate("Dialog", "Zoom+"))
        self.NEXT_3.setText(_translate("Dialog", "IN PHIẾU KHÁM"))
        self.NEXT_7.setText(_translate("Dialog", "Đóng"))
